client_id: 227304734880-es3lsept36mugmtvukir2j5820j7u7eh.apps.googleusercontent.com
google_auth: https://www.googleapis.com/oauth2/v4/token
google_contact_api: https://www.google.com/m8/feeds/contacts/default/full/?alt=json&max-results=30000